test: sol2.xml
	xmllint --schema ../../../TEI/Stylesheets/profiles/iso/schema/isotei.xsd SOL2.xml

smalltest: smalltest.xml
	xmllint --schema ../../../TEI/Stylesheets/profiles/iso/schema/isotei.xsd smalltest.xml
